# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac2c06fe9f6634a2d174770d8b2cd69d916711c1f24c1bd8400ef4ff4b6fc86752151244996b8bda9b3208b5ddab581bf1df070557384da954b2955acc9a9e4a

test:
  secret_key_base: d7518ddcf0662fc0bc44f20a64449fefc637c4f6a78acf610079e0b221e2b519c310b6103d0ed74369faf875e75051455401bb607cd1c4fadfb50be3a444db33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
